// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{
"name": "TestMessagePlugin",
"status": true,
"description": "テスト用プラグイン",
"parameters": {
"WelcomeText": "ようこそ！",
"FontSize": "28",
"Picture": "img/pictures/立ち絵",
"Title": "\"冒険の書\""
}
},
{
"name": "NestedPlugin",
"status": true,
"description": "",
"parameters": {
"Messages": "[\"{\\\"text\\\": \\\"こんにちは\\\", \\\"id\\\": \\\"1\\\"}\"]"
}
}
];
