"""Pre-built glossary of common Japanese terms for RPG/adult game translation.

Users can load these from the Settings > Glossary tab. Each category can be
loaded independently. Entries never overwrite user-defined glossary terms.
"""

# ── Body / anatomy ──────────────────────────────────────────────
BODY = {
    "おまんこ": "pussy",
    "マンコ": "pussy",
    "まんこ": "pussy",
    "おちんちん": "cock",
    "ちんちん": "cock",
    "チンポ": "cock",
    "ちんぽ": "cock",
    "チンコ": "cock",
    "ペニス": "penis",
    "おっぱい": "breasts",
    "オッパイ": "breasts",
    "おしり": "butt",
    "お尻": "butt",
    "クリトリス": "clit",
    "アナル": "anal",
    "子宮": "womb",
    "膣": "vagina",
    "乳首": "nipples",
    "乳房": "breasts",
    "陰茎": "penis",
    "睾丸": "testicles",
    "金玉": "balls",
    "太もも": "thighs",
    "恥丘": "pubic mound",
    "お股": "crotch",
    "秘部": "genitals",
    "尻": "ass",
    "胸": "breasts",
    "腰": "waist",
    "股間": "crotch",
    "肛門": "anus",
    "亀頭": "glans",
    "乳輪": "areola",
    "肉棒": "cock",
}

# ── Sexual acts / states ────────────────────────────────────────
ACTS = {
    "セックス": "sex",
    "フェラ": "blowjob",
    "フェラチオ": "fellatio",
    "パイズリ": "titjob",
    "手コキ": "handjob",
    "クンニ": "cunnilingus",
    "中出し": "creampie",
    "顔射": "facial",
    "射精": "ejaculation",
    "絶頂": "climax",
    "オーガズム": "orgasm",
    "イク": "cumming",
    "いく": "cumming",
    "レイプ": "rape",
    "輪姦": "gang rape",
    "和姦": "consensual sex",
    "処女": "virgin",
    "童貞": "virgin",
    "妊娠": "pregnancy",
    "種付け": "impregnation",
    "搾乳": "milking",
    "潮吹き": "squirting",
    "媚薬": "aphrodisiac",
    "催眠": "hypnosis",
    "触手": "tentacle",
    "孕ませ": "impregnation",
    "寝取り": "cuckolding",
    "寝取られ": "netorare",
    "痴漢": "groping",
    "露出": "exhibitionism",
    "調教": "training",
    "奴隷": "slave",
    "淫乱": "lewd",
    "変態": "pervert",
    "エッチ": "lewd",
    "おかず": "fap material",
    "オナニー": "masturbation",
    "ザーメン": "cum",
    "勃起": "erection",
    "膣内": "vaginal",
    "挿入": "penetration",
    "精液": "semen",
    "性感帯": "erogenous zone",
    "我慢汁": "precum",
    "口内射精": "oral creampie",
    "手マン": "fingering",
    "前戯": "foreplay",
    "ロリコン": "lolicon",
    "イラマチオ": "irrumatio",
    "素股": "thighjob",
    "尻コキ": "assjob",
    "ぶっかけ": "cumshot",
    "受精": "fertilized",
    "出産": "childbirth",
    "キス": "kiss",
    "膣内射精": "creampie",
    "膣外射精": "non-creampie",
    "乳揉まれ": "fondled",
    "尻揉まれ": "ass groped",
    "愛撫": "caress",
    "陵辱": "violation",
    "乱交": "orgy",
    "逆レイプ": "reverse rape",
    "夜這い": "night crawling",
    "淫語": "dirty talk",
    "喘ぎ声": "moaning",
    "母乳": "breast milk",
    "異種姦": "interspecies sex",
    "近親相姦": "incest",
    "二穴": "double penetration",
    "愛液": "love juice",
    "淫紋": "lewd crest",
    "強姦": "rape",
    "精飲": "cum drinking",
}

# ── RPG / game terms ────────────────────────────────────────────
RPG = {
    # Roles & archetypes
    "勇者": "Hero",
    "魔王": "Demon Lord",
    "魔物": "Monster",
    "冒険者": "Adventurer",
    "村人": "Villager",
    "町人": "Townsperson",
    "商人": "Merchant",
    "王": "King",
    "王女": "Princess",
    "王子": "Prince",
    "女王": "Queen",
    "領主": "Lord",
    "長老": "Elder",
    "村長": "Village Chief",
    # Locations
    "ギルド": "Guild",
    "ダンジョン": "Dungeon",
    "宿屋": "Inn",
    "酒場": "Tavern",
    "武器屋": "Weapon Shop",
    "道具屋": "Item Shop",
    "防具屋": "Armor Shop",
    "教会": "Church",
    "城": "Castle",
    "王国": "Kingdom",
    "帝国": "Empire",
    "村": "Village",
    "町": "Town",
    "迷宮": "Labyrinth",
    "塔": "Tower",
    "洞窟": "Cave",
    "森": "Forest",
    "砂漠": "Desert",
    "火山": "Volcano",
    "遺跡": "Ruins",
    "神殿": "Temple",
    "墓地": "Graveyard",
    "闘技場": "Arena",
    # Core systems
    "魔法": "Magic",
    "スキル": "Skill",
    "経験値": "EXP",
    "レベルアップ": "Level Up",
    "ゴールド": "Gold",
    "ポーション": "Potion",
    "エリクサー": "Elixir",
    "仲間": "Companion",
    "装備": "Equipment",
    "クエスト": "Quest",
    "依頼": "Request",
    "報酬": "Reward",
    "宝箱": "Treasure Chest",
    "セーブ": "Save",
    "ロード": "Load",
    "ゲームオーバー": "Game Over",
    "全滅": "Annihilation",
    # Menu / UI
    "並び替え": "Sort",
    "最強装備": "Optimal Equipment",
    "大事なもの": "Key Items",
    "ゲーム終了": "Quit Game",
    "コンティニュー": "Continue",
    "ニューゲーム": "New Game",
    "購入する": "Buy",
    "売却する": "Sell",
    "全て外す": "Unequip All",
    "キャンセル": "Cancel",
    "オプション": "Options",
    "タイトルへ": "To Title",
    "ステータス": "Status",
    "やっぱりやめる": "Never mind",
    "初めから": "Start",
    "回想する": "Recollection",
    "討伐": "Extermination",
    "邪気": "Miasma",
    "所持金": "Money",
    "持ち物": "Inventory",
    "道具": "Items",
    "使う": "Use",
    "捨てる": "Discard",
    "確認": "Confirm",
    "戻る": "Back",
    "決定": "OK",
    "次へ": "Next",
    "閉じる": "Close",
    # Locations
    "避暑地": "Summer Resort",
    "別荘": "Villa",
    "雑木林": "Thicket",
    "川辺": "Riverbank",
}

# ── Combat / battle ──────────────────────────────────────────────
COMBAT = {
    # Targeting
    "敵単体": "Single Enemy",
    "敵全体": "All Enemies",
    "敵１体": "One Enemy",
    "敵２体": "Two Enemies",
    "味方単体": "Single Ally",
    "味方全体": "All Allies",
    "味方一人": "One Ally",
    "使用者": "User",
    "自分": "Self",
    "ランダム": "Random",
    # Actions
    "攻撃": "Attack",
    "防御": "Defend",
    "逃げる": "Escape",
    "逃走": "Escape",
    "戦う": "Fight",
    "アイテム": "Item",
    "必殺技": "Special Move",
    "奥義": "Secret Art",
    "詠唱": "Chanting",
    "召喚": "Summon",
    "回復": "Recovery",
    "治療": "Heal",
    "蘇生": "Revive",
    "復活": "Revival",
    "反撃": "Counter",
    "連続攻撃": "Combo Attack",
    "全体攻撃": "Area Attack",
    "先制攻撃": "Preemptive Strike",
    "不意打ち": "Ambush",
    "会心の一撃": "Critical Hit",
    "会心": "Critical",
    "命中": "Hit",
    "回避": "Evasion",
    "ミス": "Miss",
    # Status effects
    "毒": "Poison",
    "麻痺": "Paralysis",
    "睡眠": "Sleep",
    "暗闇": "Blindness",
    "沈黙": "Silence",
    "混乱": "Confusion",
    "石化": "Petrification",
    "即死": "Instant Death",
    "戦闘不能": "Knocked Out",
    "気絶": "Stunned",
    "出血": "Bleeding",
    "呪い": "Curse",
    "狂戦士": "Berserk",
    "魔法反射": "Magic Reflection",
    "無敵": "Invincible",
    "透明": "Invisible",
    "再生": "Regeneration",
    "弱点": "Weakness",
    "耐性": "Resistance",
    "吸収": "Absorb",
    "バフ": "Buff",
    "デバフ": "Debuff",
    # Elements
    "火": "Fire",
    "氷": "Ice",
    "雷": "Thunder",
    "水": "Water",
    "風": "Wind",
    "土": "Earth",
    "光": "Light",
    "闇": "Darkness",
    "聖": "Holy",
    "無": "None",
    "物理": "Physical",
    "神聖": "Holy",
    "暗黒": "Dark",
    "木": "Wood",
    "地": "Earth",
    "凍結": "Frozen",
    "炎": "Flame",
    "大地": "Earth",
    "ダメージ": "Damage",
    "黒魔法": "Black Magic",
    "白魔法": "White Magic",
    "全体": "All",
    "敵": "Enemy",
    "味方": "Ally",
    "属性": "Attribute",
    # Additional
    "状態異常": "Status Ailment",
    "ターン終了": "End Turn",
    "不死身": "Immortal",
    "激昂": "Enraged",
}

# ── Stats / parameters ───────────────────────────────────────────
STATS = {
    "最大ＨＰ": "Max HP",
    "最大ＭＰ": "Max MP",
    "ＨＰ": "HP",
    "ＭＰ": "MP",
    "ＴＰ": "TP",
    "攻撃力": "Attack",
    "防御力": "Defense",
    "魔力": "Magic Power",
    "魔法攻撃": "Magic Attack",
    "魔法防御": "Magic Defense",
    "魔防": "Magic Defense",
    "敏捷性": "Agility",
    "敏捷": "Agility",
    "素早さ": "Speed",
    "運": "Luck",
    "命中率": "Hit Rate",
    "回避率": "Evasion Rate",
    "会心率": "Critical Rate",
    "体力": "Stamina",
    "知力": "Intelligence",
    "精神": "Spirit",
    "魅力": "Charisma",
    "力": "Strength",
    "知性": "Intelligence",
    "器用": "Dexterity",
    "職業": "Job",
    "特技": "Special Skill",
    "技": "Technique",
}

# ── Equipment / items ────────────────────────────────────────────
EQUIPMENT = {
    # Slots
    "武器": "Weapon",
    "盾": "Shield",
    "頭防具": "Headgear",
    "身体防具": "Body Armor",
    "腕防具": "Arm Guard",
    "装飾品": "Accessory",
    # Weapon types
    "剣": "Sword",
    "大剣": "Greatsword",
    "短剣": "Dagger",
    "槍": "Spear",
    "斧": "Axe",
    "弓": "Bow",
    "杖": "Staff",
    "本": "Book",
    "鞭": "Whip",
    "爪": "Claws",
    "拳": "Fist",
    "銃": "Gun",
    "刀": "Katana",
    # Items
    "薬草": "Herb",
    "毒消し": "Antidote",
    "万能薬": "Panacea",
    "魔法の鍵": "Magic Key",
    "テント": "Tent",
    "聖水": "Holy Water",
    "煙玉": "Smoke Bomb",
    "鉱石": "Ore",
    "素材": "Material",
    "レシピ": "Recipe",
    "防具": "Armor",
    "帽子": "Hat",
    "服": "Clothes",
    "指輪": "Ring",
}

# ── Eroge status / corruption ──────────────────────────────────
STATUS = {
    "好感度": "Affection",
    "淫乱度": "Lewdness",
    "堕落": "Corruption",
    "純潔": "Purity",
    "貞操": "Chastity",
    "快楽": "Pleasure",
    "感度": "Sensitivity",
    "恥辱": "Shame",
    "屈辱": "Humiliation",
    "服従": "Submission",
    "支配": "Domination",
    "魅了": "Charm",
    "誘惑": "Seduction",
    "欲情": "Lust",
    "発情": "In Heat",
    "興奮": "Arousal",
    "売春": "Prostitution",
    "娼婦": "Prostitute",
    "遊郭": "Brothel",
    "ハーレム": "Harem",
    "逆ハーレム": "Reverse Harem",
    "愛人": "Lover",
    "恋人": "Lover",
    "許嫁": "Fiance",
    "婚約者": "Fiance",
    "理性": "Sanity",
    "性欲": "Libido",
    "絶頂回数": "Orgasms",
    "経験人数": "Partners",
    "射精量": "Cum Amount",
    "恐怖": "Fear",
    "洗脳": "Brainwashing",
    "信頼度": "Trust",
    "妊娠回数": "Pregnancies",
}

# ── Fantasy races / classes ────────────────────────────────────
RACES = {
    "エルフ": "Elf",
    "ダークエルフ": "Dark Elf",
    "ドワーフ": "Dwarf",
    "獣人": "Beastkin",
    "竜人": "Dragonkin",
    "吸血鬼": "Vampire",
    "サキュバス": "Succubus",
    "インキュバス": "Incubus",
    "ゴブリン": "Goblin",
    "オーク": "Orc",
    "スライム": "Slime",
    "オーガ": "Ogre",
    "リッチ": "Lich",
    "ゾンビ": "Zombie",
    "ケルベロス": "Cerberus",
    "ミノタウロス": "Minotaur",
    "ラミア": "Lamia",
    "ハーピー": "Harpy",
    "アラクネ": "Arachne",
    "ケンタウロス": "Centaur",
    "マーメイド": "Mermaid",
    "妖精": "Fairy",
    "天使": "Angel",
    "悪魔": "Demon",
    "魔族": "Demon Race",
    "人間": "Human",
    "戦士": "Warrior",
    "魔法使い": "Mage",
    "僧侶": "Priest",
    "盗賊": "Thief",
    "騎士": "Knight",
    "聖騎士": "Paladin",
    "暗黒騎士": "Dark Knight",
    "忍者": "Ninja",
    "侍": "Samurai",
    "召喚士": "Summoner",
    "錬金術師": "Alchemist",
    "踊り子": "Dancer",
    "姫騎士": "Princess Knight",
    "女騎士": "Female Knight",
    "女戦士": "Female Warrior",
    "魔女": "Witch",
    "巫女": "Shrine Maiden",
    "シスター": "Sister",
    "メイド": "Maid",
    "くノ一": "Kunoichi",
    "魔術師": "Sorcerer",
    "大魔導士": "Archmage",
    "忍び": "Shinobi",
    # Demons / angels / monsters
    "聖女": "Saintess",
    "上級悪魔": "Arch Demon",
    "魔神": "Devil",
    "魔人": "Demon",
    "睡魔": "Mare",
    "淫魔": "Succubus",
    "夢魔": "Succubus",
    "大天使": "Archangel",
    "権天使": "Principality",
    "能天使": "Power",
    "力天使": "Virtue",
    "主天使": "Dominion",
    "智天使": "Cherub",
    "飛天魔": "Nephilim",
    "堕天使": "Fallen Angel",
    "鬼": "Oni",
    "妖怪": "Yokai",
    "式神": "Shikigami",
    "幽霊": "Ghost",
    "幽鬼": "Revenant",
    "デーモン": "Daemon",
    "ローパー": "Roper",
    "人型": "Humanoid",
    "獣型": "Beast",
    "触手型": "Tentacle Type",
    "軟体型": "Slime Type",
    "虫型": "Insect Type",
    "竜": "Dragon",
    "ドラゴン": "Dragon",
    "ワーウルフ": "Werewolf",
    "グリフォン": "Griffin",
    "ゴーレム": "Golem",
    "トロール": "Troll",
    "キメラ": "Chimera",
    "ワイバーン": "Wyvern",
    "フェニックス": "Phoenix",
    "狼": "Wolf",
    "蜘蛛": "Spider",
    "蝙蝠": "Bat",
    "蛇": "Snake",
}

# ── Clothing / attire ──────────────────────────────────────────
CLOTHING = {
    "鎧": "Armor",
    "ローブ": "Robe",
    "ビキニアーマー": "Bikini Armor",
    "レオタード": "Leotard",
    "制服": "Uniform",
    "水着": "Swimsuit",
    "下着": "Underwear",
    "パンツ": "Panties",
    "ショーツ": "Panties",
    "ブラ": "Bra",
    "ストッキング": "Stockings",
    "ガーターベルト": "Garter Belt",
    "ニーソックス": "Thigh-Highs",
    "チャイナドレス": "Cheongsam",
    "バニースーツ": "Bunny Suit",
    "メイド服": "Maid Outfit",
    "巫女服": "Shrine Maiden Outfit",
    "拘束具": "Restraints",
    "首輪": "Collar",
    "手枷": "Handcuffs",
    "目隠し": "Blindfold",
    "猿轡": "Ball Gag",
    "タイツ": "Tights",
    "エプロン": "Apron",
    "スカート": "Skirt",
    "ドレス": "Dress",
    "マント": "Cloak",
    "着物": "Kimono",
    "浴衣": "Yukata",
    "体操服": "Gym Uniform",
    "ブルマ": "Bloomers",
    "スクール水着": "School Swimsuit",
}

# ── Gambling / poker ─────────────────────────────────────────────
GAMBLING = {
    # Card games
    "ポーカー": "poker",
    "ブラックジャック": "blackjack",
    "バカラ": "baccarat",
    "トランプ": "playing cards",
    "カード": "card",
    "手札": "hand",
    "山札": "deck",
    "切り札": "trump card",
    "ジョーカー": "joker",
    "ババ抜き": "Old Maid",
    "神経衰弱": "Concentration",
    "大富豪": "President",
    "七並べ": "Sevens",
    # Poker hands
    "ロイヤルストレートフラッシュ": "royal flush",
    "ストレートフラッシュ": "straight flush",
    "フォーカード": "four of a kind",
    "フルハウス": "full house",
    "フラッシュ": "flush",
    "ストレート": "straight",
    "スリーカード": "three of a kind",
    "ツーペア": "two pair",
    "ワンペア": "one pair",
    "ブタ": "high card",
    "役": "hand",
    # Poker actions
    "レイズ": "raise",
    "コール": "call",
    "フォールド": "fold",
    "チェック": "check",
    "ベット": "bet",
    "オールイン": "all-in",
    "ブラフ": "bluff",
    "ディーラー": "dealer",
    # Gambling general
    "ギャンブル": "gambling",
    "賭け": "bet",
    "賭ける": "to bet",
    "カジノ": "casino",
    "スロット": "slot machine",
    "ルーレット": "roulette",
    "サイコロ": "dice",
    "チップ": "chips",
    "配当": "payout",
    "倍率": "odds",
    "大当たり": "jackpot",
    "ジャックポット": "jackpot",
    "一攫千金": "hitting the jackpot",
    "勝負": "match",
    "勝ち": "win",
    "負け": "loss",
    "引き分け": "draw",
    "イカサマ": "cheating",
    "いかさま": "cheating",
    # Strip poker / penalty games
    "脱衣ポーカー": "strip poker",
    "脱衣麻雀": "strip mahjong",
    "脱衣": "stripping",
    "脱ぐ": "undress",
    "脱がす": "strip someone",
    "脱がされる": "get stripped",
    "罰ゲーム": "penalty game",
    "罰": "penalty",
    "一枚脱ぐ": "take off one piece",
    "全裸": "fully nude",
    "半裸": "half-naked",
    "裸": "naked",
    "恥ずかしい": "embarrassing",
    "丸見え": "fully exposed",
    "見せる": "show",
    "晒す": "expose",
    "賭け事": "gambling",
    "負けたら脱ぐ": "strip if you lose",
}

# ── Speaker tags / honorifics ────────────────────────────────────
SPEAKERS = {
    "ご主人様": "Master",
    "マスター": "Master",
    "お嬢様": "Milady",
    "旦那様": "Master",
    "奥様": "Madam",
    "先生": "Teacher",
    "先輩": "Senpai",
    "後輩": "Junior",
    "お兄ちゃん": "Big Brother",
    "お姉ちゃん": "Big Sister",
    "お兄さん": "Mister",
    "お姉さん": "Miss",
    "おじさん": "Old Man",
    "おばさん": "Lady",
    "男": "Man",
    "女": "Woman",
    "少年": "Boy",
    "少女": "Girl",
    "青年": "Young Man",
    "老人": "Old Man",
    "兵士": "Soldier",
    "衛兵": "Guard",
    "店主": "Shopkeeper",
    "受付嬢": "Receptionist",
    "魔法少女": "Magical Girl",
    "ナレーション": "Narration",
    "令嬢": "Young Lady",
    "小悪魔": "Little Devil",
    "付き人": "Attendant",
    "村人たち": "Villagers",
}

# ── Common expressions ──────────────────────────────────────────
EXPRESSIONS = {
    "くっ": "Kuh...",
    "ふふ": "Fufu",
    "うふふ": "Ufufu",
    "あはは": "Ahaha",
    "えへへ": "Ehehe",
    "くすくす": "Hehe",
    "ぐぬぬ": "Grr...",
    "きゃー": "Kyaa!",
    "やだ": "No way",
    "ちょっと": "Hey",
    "すごい": "Amazing",
    "やめて": "Stop it",
    "ダメ": "No",
    "だめ": "No",
    "お願い": "Please",
    "ありがとう": "Thank you",
    "ごめんなさい": "I'm sorry",
    "ごめんね": "Sorry",
    "バカ": "Idiot",
    "馬鹿": "Idiot",
    "うるさい": "Shut up",
    "助けて": "Help me",
    "気持ちいい": "It feels good",
    "いやらしい": "Naughty",
    "メスガキ": "bratty girl",
    "クソガキ": "brat",
    "ガキ": "brat",
    "あん": "Ahn~",
    "んっ": "Mmh",
    "痛い": "It hurts",
    "怖い": "Scary",
    "嬉しい": "Happy",
    "熱い": "Hot",
}

# ── Onomatopoeia / SFX ───────────────────────────────────────────
ONOMATOPOEIA = {
    "ぬるぬる": "slippery",
    "ぷにぷに": "soft and squishy",
    "シコシコ": "stroking",
    "ビンビン": "rock hard",
    "ドピュ": "spurt",
    "ビクビク": "twitching",
    "パンパン": "slapping",
    "ぐちゅぐちゅ": "squelching",
    "ズボズボ": "thrusting",
    "つるつる": "smooth",
    "ドクドク": "throbbing",
    "ヌルヌル": "slippery",
    "ピクピク": "twitching",
    "ズブズブ": "plunging",
    "ジュボジュボ": "slurping",
}

# ── All categories with labels ──────────────────────────────────
CATEGORIES = {
    "Body / Anatomy": BODY,
    "Sexual Acts": ACTS,
    "Status / Corruption": STATUS,
    "Fantasy Races / Classes": RACES,
    "Clothing / Attire": CLOTHING,
    "Gambling / Poker": GAMBLING,
    "RPG Terms": RPG,
    "Combat / Battle": COMBAT,
    "Stats / Parameters": STATS,
    "Equipment / Items": EQUIPMENT,
    "Speaker Tags": SPEAKERS,
    "Common Expressions": EXPRESSIONS,
    "Onomatopoeia / SFX": ONOMATOPOEIA,
}


def get_all_defaults() -> dict:
    """Return all default glossary entries merged into one dict."""
    merged = {}
    for cat_entries in CATEGORIES.values():
        merged.update(cat_entries)
    return merged
